#!/usr/bin/env python3
"""Generated by Copilot: Diagnose UDP send path with optional local bind."""

import argparse
import socket
import sys


def probe(target_ip: str, target_port: int, local_ip: str | None, payload: bytes) -> int:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        if local_ip:
            sock.bind((local_ip, 0))
        print(f"local={sock.getsockname()} target=({target_ip}, {target_port})")
        sent = sock.sendto(payload, (target_ip, target_port))
        print(f"sendto=OK bytes={sent}")
        return 0
    except OSError as error:
        print(f"sendto=FAIL errno={error.errno} msg={error}")
        return 1
    finally:
        sock.close()


def main() -> int:
    parser = argparse.ArgumentParser(description="UDP route/interface probe")
    parser.add_argument("--target-ip", required=True, help="Target IPv4 address")
    parser.add_argument("--target-port", required=True, type=int, help="Target UDP port")
    parser.add_argument("--local-ip", default=None, help="Optional local IPv4 source bind")
    parser.add_argument("--payload", default="test\\n", help="Payload text")
    args = parser.parse_args()

    return probe(args.target_ip, args.target_port, args.local_ip, args.payload.encode())


if __name__ == "__main__":
    sys.exit(main())
