#include <Arduino.h>
#include <ArduinoOTA.h>
#include <ESP8266HTTPUpdateServer.h>
#include <ESP8266WebServer.h>
#include <ESP8266WiFi.h>
#include <LittleFS.h>

#ifndef WIFI_SSID
#error WIFI_SSID is not defined. Fill esp8266-target/.env before building.
#endif

#ifndef WIFI_PASSWORD
#error WIFI_PASSWORD is not defined. Fill esp8266-target/.env before building.
#endif

#ifndef OTA_HOSTNAME
#error OTA_HOSTNAME is not defined. Fill esp8266-target/.env before building.
#endif

#ifndef SERIAL_BAUD
#define SERIAL_BAUD 115200
#endif

#ifndef WIFI_CONNECT_TIMEOUT_MS
#define WIFI_CONNECT_TIMEOUT_MS 15000UL
#endif

#ifndef REMOTE_SIGNAL_BAUD
#define REMOTE_SIGNAL_BAUD 9600
#endif

#ifndef REMOTE_SIGNAL_RX_PIN
#define REMOTE_SIGNAL_RX_PIN 3
#endif

#ifndef FAN_RELAY_1_PIN
#define FAN_RELAY_1_PIN 14
#endif

#ifndef FAN_RELAY_2_PIN
#define FAN_RELAY_2_PIN 12
#endif

#ifndef FAN_RELAY_3_PIN
#define FAN_RELAY_3_PIN 15
#endif

#ifndef OTA_PORT
#define OTA_PORT 8266
#endif

#ifndef FALLBACK_AP_SSID
#define FALLBACK_AP_SSID "ifan04-setup"
#endif

#ifndef FALLBACK_AP_PASSWORD
#define FALLBACK_AP_PASSWORD ""
#endif

namespace
{
  enum class FanSpeed
  {
    Off,
    Low,
    Mid,
    High,
  };

  struct Config
  {
    String wifiSsid;
    String wifiPassword;
    String otaHostname;
    String fallbackApSsid;
    String fallbackApPassword;
  };

  const unsigned long kConnectTimeoutMs = WIFI_CONNECT_TIMEOUT_MS;
  constexpr char kConfigPath[] = "/config.txt";
  constexpr size_t kMaxSignalBufferBytes = 128;
  constexpr unsigned long kSignalFrameGapMs = 40;
  constexpr uint16_t kRemoteHeader = 0xAA55;
  constexpr uint16_t kRemoteHighFan = 0x0104;
  constexpr uint32_t kRemoteLowFanOff = 0x000100;
  constexpr uint32_t kRemoteLowFanLow = 0x000101;
  constexpr uint32_t kRemoteLowFanMid = 0x000102;
  constexpr uint32_t kRemoteLowFanHigh = 0x000103;

  Config activeConfig = {
      WIFI_SSID,
      WIFI_PASSWORD,
      OTA_HOSTNAME,
      FALLBACK_AP_SSID,
      FALLBACK_AP_PASSWORD,
  };
  // Generated by Copilot: Web updater as cable-free fallback when espota is blocked.
  ESP8266HTTPUpdateServer httpUpdater;
  ESP8266WebServer webServer(80);
  String signalBuffer;
  unsigned long lastSignalByteAtMs = 0;
  unsigned long scheduledRestartAtMs = 0;
  bool wifiConnected = false;
  bool fallbackApActive = false;
  bool otaReady = false;
  bool relay1State = false;
  bool relay2State = false;
  bool relay3State = false;
  FanSpeed currentFanSpeed = FanSpeed::Off;

  String htmlEscape(const String &value)
  {
    String escaped;
    escaped.reserve(value.length() + 16);

    for (size_t index = 0; index < value.length(); ++index)
    {
      switch (value[index])
      {
      case '&':
        escaped += F("&amp;");
        break;
      case '<':
        escaped += F("&lt;");
        break;
      case '>':
        escaped += F("&gt;");
        break;
      case '"':
        escaped += F("&quot;");
        break;
      case '\'':
        escaped += F("&#39;");
        break;
      default:
        escaped += value[index];
        break;
      }
    }

    return escaped;
  }

  String jsonEscape(const String &value)
  {
    String escaped;
    escaped.reserve(value.length() + 16);

    for (size_t index = 0; index < value.length(); ++index)
    {
      const char current = value[index];

      switch (current)
      {
      case '\\':
        escaped += F("\\\\");
        break;
      case '"':
        escaped += F("\\\"");
        break;
      case '\n':
        escaped += F("\\n");
        break;
      case '\r':
        escaped += F("\\r");
        break;
      case '\t':
        escaped += F("\\t");
        break;
      default:
        escaped += current;
        break;
      }
    }

    return escaped;
  }

  String currentIpAddress()
  {
    return fallbackApActive ? WiFi.softAPIP().toString() : WiFi.localIP().toString();
  }

  String fanSpeedLabel(const FanSpeed speed)
  {
    switch (speed)
    {
    case FanSpeed::Low:
      return F("low");
    case FanSpeed::Mid:
      return F("mid");
    case FanSpeed::High:
      return F("high");
    case FanSpeed::Off:
    default:
      return F("off");
    }
  }

  void setFanRelayStates(const bool relay1, const bool relay2, const bool relay3)
  {
    relay1State = relay1;
    relay2State = relay2;
    relay3State = relay3;

    digitalWrite(FAN_RELAY_1_PIN, relay1State ? HIGH : LOW);
    digitalWrite(FAN_RELAY_2_PIN, relay2State ? HIGH : LOW);
    digitalWrite(FAN_RELAY_3_PIN, relay3State ? HIGH : LOW);
  }

  void applyFanSpeed(const FanSpeed speed)
  {
    currentFanSpeed = speed;

    switch (speed)
    {
    case FanSpeed::Low:
      setFanRelayStates(true, false, false);
      break;
    case FanSpeed::Mid:
      setFanRelayStates(true, true, false);
      break;
    case FanSpeed::High:
      setFanRelayStates(false, false, true);
      break;
    case FanSpeed::Off:
    default:
      setFanRelayStates(false, false, false);
      break;
    }

    Serial.print(F("Fan speed changed to: "));
    Serial.println(fanSpeedLabel(speed));
  }

  uint8_t commandChecksum(const uint8_t *frame)
  {
    uint16_t sum = 0;
    for (size_t index = 2; index <= 6; ++index)
    {
      sum += frame[index];
    }
    return static_cast<uint8_t>(sum & 0xFF);
  }

  bool parseRemoteFrame(const uint8_t *frame)
  {
    const uint16_t header = static_cast<uint16_t>(frame[0] << 8) | frame[1];
    if (header != kRemoteHeader)
    {
      return false;
    }

    if (commandChecksum(frame) != frame[7])
    {
      return false;
    }

    const uint16_t commandHigh = static_cast<uint16_t>(frame[2] << 8) | frame[3];
    const uint32_t commandLow = (static_cast<uint32_t>(frame[4]) << 16) |
                                (static_cast<uint32_t>(frame[5]) << 8) |
                                static_cast<uint32_t>(frame[6]);

    if (commandHigh != kRemoteHighFan)
    {
      return true;
    }

    if (commandLow == kRemoteLowFanOff)
    {
      applyFanSpeed(FanSpeed::Off);
      return true;
    }

    if (commandLow == kRemoteLowFanLow)
    {
      applyFanSpeed(FanSpeed::Low);
      return true;
    }

    if (commandLow == kRemoteLowFanMid)
    {
      applyFanSpeed(FanSpeed::Mid);
      return true;
    }

    if (commandLow == kRemoteLowFanHigh)
    {
      applyFanSpeed(FanSpeed::High);
      return true;
    }

    return true;
  }

  void processRemotePayload(const String &payload)
  {
    if (payload.length() < 8)
    {
      return;
    }

    // Generated by Copilot: Scan payload for complete 8-byte IFAN remote frames.
    for (size_t index = 0; index + 7 < payload.length(); ++index)
    {
      uint8_t frame[8];
      for (size_t offset = 0; offset < 8; ++offset)
      {
        frame[offset] = static_cast<uint8_t>(payload[index + offset]);
      }

      if (parseRemoteFrame(frame))
      {
        index += 7;
      }
    }
  }

  String currentNetworkMode()
  {
    if (wifiConnected)
    {
      return F("wifi");
    }

    if (fallbackApActive)
    {
      return F("ap");
    }

    return F("offline");
  }

  String fallbackApSsidWithChipId()
  {
    String ssid = activeConfig.fallbackApSsid;
    if (ssid.length() == 0)
    {
      ssid = F("ifan04");
    }

    ssid += '-';
    ssid += String(ESP.getChipId(), HEX);
    return ssid;
  }

  void persistConfig()
  {
    File configFile = LittleFS.open(kConfigPath, "w");
    if (!configFile)
    {
      Serial.println(F("Failed to open config file for writing"));
      return;
    }

    configFile.printf("WIFI_SSID=%s\n", activeConfig.wifiSsid.c_str());
    configFile.printf("WIFI_PASSWORD=%s\n", activeConfig.wifiPassword.c_str());
    configFile.printf("OTA_HOSTNAME=%s\n", activeConfig.otaHostname.c_str());
    configFile.printf("FALLBACK_AP_SSID=%s\n", activeConfig.fallbackApSsid.c_str());
    configFile.printf("FALLBACK_AP_PASSWORD=%s\n", activeConfig.fallbackApPassword.c_str());
    configFile.close();
  }

  void loadPersistedConfig()
  {
    if (!LittleFS.exists(kConfigPath))
    {
      return;
    }

    File configFile = LittleFS.open(kConfigPath, "r");
    if (!configFile)
    {
      Serial.println(F("Failed to open persisted config"));
      return;
    }

    while (configFile.available())
    {
      String line = configFile.readStringUntil('\n');
      line.trim();
      if (line.length() == 0 || line.startsWith("#"))
      {
        continue;
      }

      const int separator = line.indexOf('=');
      if (separator <= 0)
      {
        continue;
      }

      const String key = line.substring(0, separator);
      const String value = line.substring(separator + 1);

      if (key == F("WIFI_SSID"))
      {
        activeConfig.wifiSsid = value;
      }
      else if (key == F("WIFI_PASSWORD"))
      {
        activeConfig.wifiPassword = value;
      }
      else if (key == F("OTA_HOSTNAME"))
      {
        activeConfig.otaHostname = value;
      }
      else if (key == F("FALLBACK_AP_SSID"))
      {
        activeConfig.fallbackApSsid = value;
      }
      else if (key == F("FALLBACK_AP_PASSWORD"))
      {
        activeConfig.fallbackApPassword = value;
      }
    }

    configFile.close();
  }

  void clearPersistedConfig()
  {
    if (LittleFS.exists(kConfigPath))
    {
      LittleFS.remove(kConfigPath);
    }
  }

  void storeSignalFrame(const String &payload)
  {
    if (payload.length() == 0)
    {
      return;
    }

    processRemotePayload(payload);
  }

  void flushSignalBuffer()
  {
    if (signalBuffer.length() == 0)
    {
      return;
    }

    storeSignalFrame(signalBuffer);
    signalBuffer = "";
  }

  bool connectToWifi()
  {
    WiFi.persistent(false);
    WiFi.mode(WIFI_STA);
    WiFi.hostname(activeConfig.otaHostname);
    WiFi.begin(activeConfig.wifiSsid.c_str(), activeConfig.wifiPassword.c_str());

    Serial.print(F("Connecting to WiFi"));

    const unsigned long startMs = millis();
    while (WiFi.status() != WL_CONNECTED && millis() - startMs < kConnectTimeoutMs)
    {
      delay(500);
      Serial.print('.');
    }

    Serial.println();

    wifiConnected = WiFi.status() == WL_CONNECTED;
    fallbackApActive = false;

    if (!wifiConnected)
    {
      Serial.println(F("WiFi connection failed, switching to fallback AP"));
      return false;
    }

    Serial.print(F("WiFi connected, IP: "));
    Serial.println(WiFi.localIP());
    Serial.print(F("OTA target IP: "));
    Serial.println(WiFi.localIP());
    return true;
  }

  void startFallbackAp()
  {
    const String fallbackSsid = fallbackApSsidWithChipId();
    const String fallbackPassword = activeConfig.fallbackApPassword;

    WiFi.disconnect();
    WiFi.mode(WIFI_AP);

    const bool started = fallbackPassword.length() >= 8
                             ? WiFi.softAP(fallbackSsid.c_str(), fallbackPassword.c_str())
                             : WiFi.softAP(fallbackSsid.c_str());

    wifiConnected = false;
    fallbackApActive = started;

    if (!started)
    {
      Serial.println(F("Failed to start fallback AP"));
      return;
    }

    Serial.print(F("Fallback AP started: "));
    Serial.println(fallbackSsid);
    Serial.print(F("AP IP: "));
    Serial.println(WiFi.softAPIP());

    if (fallbackPassword.length() >= 8)
    {
      Serial.println(F("AP uses the configured password"));
    }
    else
    {
      Serial.println(F("AP is open because FALLBACK_AP_PASSWORD is empty or too short"));
    }
  }

  void setupOta()
  {
    if (WiFi.status() != WL_CONNECTED)
    {
      otaReady = false;
      return;
    }

    if (otaReady)
    {
      return;
    }

    // Generated by Copilot: Keep WiFi fully awake to reduce OTA invite drops.
    WiFi.setSleepMode(WIFI_NONE_SLEEP);
    ArduinoOTA.setPort(OTA_PORT);
    ArduinoOTA.setHostname(activeConfig.otaHostname.c_str());
    ArduinoOTA.onStart([]()
                       { Serial.println(F("OTA update started")); });
    ArduinoOTA.onEnd([]()
                     { Serial.println(F("OTA update finished")); });
    ArduinoOTA.onError([](ota_error_t error)
                       { Serial.printf("OTA error: %u\n", static_cast<unsigned>(error)); });
    ArduinoOTA.begin();
    otaReady = true;

    Serial.print(F("ArduinoOTA ready as: "));
    Serial.println(activeConfig.otaHostname);
    Serial.print(F("ArduinoOTA port: "));
    Serial.println(OTA_PORT);
  }

  void handleRoot()
  {
    const String apName = fallbackApSsidWithChipId();
    String html = F(
        "<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>iFan04 Control</title><style>body{font-family:Arial,sans-serif;background:#f4f1ea;color:#1d1d1d;margin:0;padding:24px;}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px;}"
        ".card{background:#fff;border-radius:16px;padding:18px;box-shadow:0 8px 24px rgba(0,0,0,.08);}"
        ".statusline{display:flex;align-items:center;gap:10px;margin:8px 0;}"
        ".dot{width:12px;height:12px;border-radius:50%;display:inline-block;background:#9ca3af;}"
        ".on{background:#16a34a;box-shadow:0 0 0 3px rgba(22,163,74,.2);}"
        ".off{background:#9ca3af;}"
        ".speed{display:inline-block;padding:4px 10px;border-radius:999px;background:#e5e7eb;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:.06em;}"
        "h1,h2{margin-top:0;}label{display:block;margin:10px 0 4px;font-weight:600;}input{width:100%;padding:10px;border:1px solid #c9c3b8;border-radius:10px;box-sizing:border-box;}"
        "button{margin-top:14px;padding:10px 14px;border:0;border-radius:10px;background:#145a32;color:#fff;font-weight:700;cursor:pointer;}"
        ".danger{background:#922b21;}small{color:#666;}</style>"
        "<script>function setDot(id,state){const el=document.getElementById(id);el.classList.remove('on','off');el.classList.add(state?'on':'off');}"
        "async function refreshStatus(){const r=await fetch('/api/status');const d=await r.json();document.getElementById('status').textContent=d.mode;document.getElementById('ip').textContent=d.ip;document.getElementById('ssid').textContent=d.connectedSsid;document.getElementById('ota').textContent=d.otaHostname;document.getElementById('fanSpeed').textContent=d.fanSpeed;setDot('relay1Dot',d.relay1);setDot('relay2Dot',d.relay2);setDot('relay3Dot',d.relay3);}setInterval(refreshStatus,1500);window.addEventListener('load',refreshStatus);</script>"
        "</head><body><h1>Sonoff iFan04</h1><div class='grid'>");

    html += F("<section class='card'><h2>Status</h2><p><strong>Mode:</strong> <span id='status'>");
    html += htmlEscape(currentNetworkMode());
    html += F("</span></p><p><strong>IP:</strong> <span id='ip'>");
    html += htmlEscape(currentIpAddress());
    html += F("</span></p><p><strong>SSID/AP:</strong> <span id='ssid'>");
    html += htmlEscape(wifiConnected ? activeConfig.wifiSsid : apName);
    html += F("</span></p><p><strong>OTA Hostname:</strong> <span id='ota'>");
    html += htmlEscape(activeConfig.otaHostname);
    html += F("</span></p><p><strong>Fan:</strong> <span id='fanSpeed' class='speed'>");
    html += htmlEscape(fanSpeedLabel(currentFanSpeed));
    html += F("</span></p>");

    html += F("<div class='statusline'><span id='relay1Dot' class='dot ");
    html += relay1State ? F("on") : F("off");
    html += F("'></span><span>R1</span></div>");
    html += F("<div class='statusline'><span id='relay2Dot' class='dot ");
    html += relay2State ? F("on") : F("off");
    html += F("'></span><span>R2</span></div>");
    html += F("<div class='statusline'><span id='relay3Dot' class='dot ");
    html += relay3State ? F("on") : F("off");
    html += F("'></span><span>R3</span></div>");

    html += F("<h3>Control</h3><p><a href='/fan?speed=off'>Off</a> | <a href='/fan?speed=low'>Low</a> | <a href='/fan?speed=mid'>Mid</a> | <a href='/fan?speed=high'>High</a></p>");

    html += F("<small>Saved values in flash override .env defaults until cleared.</small></section>");

    html += F("</div></body></html>");

    webServer.send(200, F("text/html; charset=utf-8"), html);
  }

  void handleStatusApi()
  {
    const String apName = fallbackApSsidWithChipId();
    String json = F("{");
    json += F("\"mode\":\"");
    json += jsonEscape(currentNetworkMode());
    json += F("\",\"ip\":\"");
    json += jsonEscape(currentIpAddress());
    json += F("\",\"connectedSsid\":\"");
    json += jsonEscape(wifiConnected ? activeConfig.wifiSsid : apName);
    json += F("\",\"otaHostname\":\"");
    json += jsonEscape(activeConfig.otaHostname);
    json += F("\",\"fanSpeed\":\"");
    json += jsonEscape(fanSpeedLabel(currentFanSpeed));
    json += F(",\"relay1\":");
    json += relay1State ? F("true") : F("false");
    json += F(",\"relay2\":");
    json += relay2State ? F("true") : F("false");
    json += F(",\"relay3\":");
    json += relay3State ? F("true") : F("false");
    json += F("}");
    webServer.send(200, F("application/json"), json);
  }

  void handleSetFanSpeed()
  {
    const String speed = webServer.arg("speed");

    if (speed == F("off"))
    {
      applyFanSpeed(FanSpeed::Off);
    }
    else if (speed == F("low"))
    {
      applyFanSpeed(FanSpeed::Low);
    }
    else if (speed == F("mid"))
    {
      applyFanSpeed(FanSpeed::Mid);
    }
    else if (speed == F("high"))
    {
      applyFanSpeed(FanSpeed::High);
    }
    else
    {
      webServer.send(400, F("text/plain"), F("invalid speed"));
      return;
    }

    webServer.sendHeader(F("Location"), F("/"));
    webServer.send(303, F("text/plain"), F("ok"));
  }

  void handleSaveConfig()
  {
    const String wifiSsid = webServer.arg("wifiSsid");
    const String otaHostname = webServer.arg("otaHostname");
    const String fallbackApPassword = webServer.arg("fallbackApPassword");

    if (wifiSsid.length() == 0 || otaHostname.length() == 0)
    {
      webServer.send(400, F("text/plain"), F("wifiSsid and otaHostname are required"));
      return;
    }

    if (fallbackApPassword.length() > 0 && fallbackApPassword.length() < 8)
    {
      webServer.send(400, F("text/plain"), F("fallbackApPassword must be empty or at least 8 characters"));
      return;
    }

    activeConfig.wifiSsid = wifiSsid;
    activeConfig.wifiPassword = webServer.arg("wifiPassword");
    activeConfig.otaHostname = otaHostname;
    activeConfig.fallbackApSsid = webServer.arg("fallbackApSsid");
    activeConfig.fallbackApPassword = fallbackApPassword;

    persistConfig();
    scheduledRestartAtMs = millis() + 1500;
    webServer.send(200, F("text/html; charset=utf-8"), F("<html><body><h1>Saved</h1><p>Configuration stored in flash. The device will restart now.</p></body></html>"));
  }

  void handleClearConfig()
  {
    clearPersistedConfig();
    scheduledRestartAtMs = millis() + 1500;
    webServer.send(200, F("text/html; charset=utf-8"), F("<html><body><h1>Cleared</h1><p>Stored configuration removed. The device will restart and use .env defaults again.</p></body></html>"));
  }

  void setupWebServer()
  {
    httpUpdater.setup(&webServer, F("/update"));
    webServer.on(F("/"), HTTP_GET, handleRoot);
    webServer.on(F("/api/status"), HTTP_GET, handleStatusApi);
    webServer.on(F("/fan"), HTTP_GET, handleSetFanSpeed);
    webServer.on(F("/config"), HTTP_POST, handleSaveConfig);
    webServer.on(F("/clear-config"), HTTP_POST, handleClearConfig);
    webServer.begin();

    Serial.println(F("Web UI ready"));
  }
} // namespace

void setup()
{
  pinMode(FAN_RELAY_1_PIN, OUTPUT);
  pinMode(FAN_RELAY_2_PIN, OUTPUT);
  pinMode(FAN_RELAY_3_PIN, OUTPUT);
  applyFanSpeed(FanSpeed::Off);

  Serial.begin(REMOTE_SIGNAL_BAUD);
  Serial.println();

  if (!LittleFS.begin())
  {
    Serial.println(F("LittleFS mount failed, formatting…"));
    LittleFS.format();
    LittleFS.begin();
  }

  loadPersistedConfig();
  Serial.println(F("ESP8266 OTA bootstrap starting"));
  Serial.printf("Listening for remote bytes on GPIO%d at %d baud\n", REMOTE_SIGNAL_RX_PIN, REMOTE_SIGNAL_BAUD);

  if (!connectToWifi())
  {
    startFallbackAp();
  }

  setupOta();
  setupWebServer();
}

void loop()
{
  while (Serial.available())
  {
    const char current = static_cast<char>(Serial.read());
    signalBuffer += current;
    if (signalBuffer.length() >= kMaxSignalBufferBytes || current == '\n' || current == '\r')
    {
      flushSignalBuffer();
    }
    lastSignalByteAtMs = millis();
  }

  if (signalBuffer.length() > 0 && millis() - lastSignalByteAtMs > kSignalFrameGapMs)
  {
    flushSignalBuffer();
  }

  setupOta();
  if (otaReady)
  {
    ArduinoOTA.handle();
  }
  webServer.handleClient();

  if (scheduledRestartAtMs != 0 && millis() >= scheduledRestartAtMs)
  {
    ESP.restart();
  }
}
